# Generated by Django 4.0.5 on 2022-06-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='owner',
        ),
    ]
