# Generated by Django 4.0.5 on 2022-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0002_remove_candidateprofile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='miejscowosc',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='zdjecie',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='age',
            field=models.CharField(blank=True, default='16-20', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(default='London', max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='sex',
            field=models.CharField(default='Unspecified', max_length=20),
        ),
    ]
