# Generated by Django 4.0.5 on 2022-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0003_remove_candidateprofile_miejscowosc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.CharField(blank=True, default='Unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=20),
        ),
    ]
