# Generated by Django 4.0.5 on 2022-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0004_alter_candidateprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.CharField(blank=True, default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Any', '')], default='Any', max_length=20),
        ),
    ]
