# Generated by Django 4.0.5 on 2022-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0005_alter_candidateprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.CharField(blank=True, choices=[('16-20', '16-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('40+', '40+'), ('Any', '')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
