# Generated by Django 4.0.5 on 2022-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0011_alter_candidateprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.CharField(choices=[('16-20', '16-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('40+', '40+'), (None, None)], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), (None, None)], max_length=20),
        ),
    ]
